builder:
  track: dev

labels:
  app: estafette-io
  team: estafette-team
  language: hugo

pipelines:
  git-clone:
    image: extensions/git-clone:dev
    shallow: false

  statify:
    image: estafette/hugo:0.42.1
    commands:
    - echo "Deleting old publication"
    - rm -rf public
    - mkdir public
    - git worktree prune
    - rm -rf .git/worktrees/public/
    - echo "Checking out gh-pages branch into public"
    - git worktree add -B gh-pages public origin/gh-pages
    - echo "Removing existing files"
    - rm -rf public/*
    - echo "Generating site"
    - hugo version
    - hugo
    - echo "Updating gh-pages branch"
    - cd public && git add --all && git commit -m "Publishing version ${ESTAFETTE_BUILD_VERSION}"
    - git push origin gh-pages
    when:
      status == 'succeeded' &&
      branch == 'master'