labels:
  app: estafette-io
  team: estafette-team
  language: hugo

pipelines:
  git-clone:
    image: extensions/git-clone:dev
    shallow: false

  statify:
    image: alpine:3.7
    commands:
    - apk add --update --no-cache hugo git openssh
    - echo "Deleting old publication"
    - rm -rf public
    - mkdir public
    - git worktree prune
    - rm -rf .git/worktrees/public/
    - echo "Checking out gh-pages branch into public"
    - git fetch origin
    - git branch -a
    - git worktree add -B gh-pages public origin/gh-pages
    - echo "Removing existing files"
    - rm -rf public/*
    - echo "Generating site"
    - hugo
    - echo "Updating gh-pages branch"
    - cd public && git add --all && git commit -m "Publishing to gh-pages"
    when:
      status == 'succeeded' &&
      branch == 'master'