baseurl = "https://estafette.io/"
title = "Estafette CI/CD"
languageCode = "en-us"
theme = "estafette"
pygmentsCodefences = true
pygmentsStyle = "abap"
pluralizeListTitles = false
disableHugoGeneratorInject = true