baseurl = "https://estafette.io/"
title = "Estafette CI/CD"
languageCode = "en-us"
theme = "estafette"
pygmentsUseClasses = true
pygmentsCodefences = true

[menu]

  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/docs/"
    weight = -100

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 50
